In [1]:
import pandas as pd

# NMI flights

In [7]:
df_nmi = pd.read_csv("google_flight_nmi.csv")
df_nmi = df_nmi.drop(columns=['Unnamed: 0'])
df_nmi.head()

,Departure_Time,Arrival_Time,Airline,Duration,Route,Stops,Layover_Time_Location,CO2_Emissions,Emissions_Change,Price,Class
0,8:00 AM,2:50 PM,IndiGo,6 hr 50 min,NMI–BLR,1 stop,3 hr 50 min KLH,88 kg CO2e,+28% emissions,"₹6,073",economy
1,11:05 AM,8:55 PM,IndiGo,9 hr 50 min,NMI–BLR,1 stop,6 hr 50 min GOI,92 kg CO2e,+33% emissions,"₹6,937",economy
2,11:05 AM,3:45 PM,IndiGo,4 hr 40 min,NMI–BLR,1 stop,1 hr 50 min GOI,92 kg CO2e,+33% emissions,"₹8,086",economy
3,7:15 PM,11:00 PM,IndiGo,3 hr 45 min,BLR–NMI,1 stop,1 hr 20 min GOI,91 kg CO2e,+32% emissions,"₹6,005",economy
4,5:40 PM,11:00 PM,IndiGo,5 hr 20 min,BLR–NMI,1 stop,2 hr 50 min GOI,91 kg CO2e,+32% emissions,"₹6,005",economy

In [9]:
len(df_nmi)

98

# BOM flights

In [8]:
df_bom = pd.read_csv("google_flight_bom.csv")
df_bom = df_bom.drop(columns=['Unnamed: 0'])
df_bom.head()

,Departure_Time,Arrival_Time,Airline,Duration,Route,Stops,Layover_Time_Location,CO2_Emissions,Emissions_Change,Price,Class
0,11:20 AM,3:45 PM,IndiGo,4 hr 25 min,BOM–BLR,1 stop,1 hr 55 min GOI,92 kg CO2e,+33% emissions,"₹4,383",economy
1,4:40 PM,10:15 PM,IndiGo,5 hr 35 min,BOM–BLR,1 stop,2 hr 50 min GOI,104 kg CO2e,+51% emissions,"₹4,383",economy
2,5:45 AM,10:55 AM,IndiGo,5 hr 10 min,BOM–BLR,1 stop,2 hr 15 min HYD,106 kg CO2e,+54% emissions,"₹4,514",economy
3,9:15 AM,1:35 PM,IndiGo,4 hr 20 min,BOM–BLR,1 stop,1 hr 45 min GOX,95 kg CO2e,+38% emissions,"₹4,514",economy
4,3:15 PM,7:05 PM,IndiGo,3 hr 50 min,BOM–BLR,1 stop,1 hr HYD,106 kg CO2e,+54% emissions,"₹4,514",economy

In [10]:
len(df_bom)

462